import './globals.scss';
import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>
            {/* <add Cookies /> */}
            <nav>
              <Link href="/" className="navText">
                Home
              </Link>

              <Link href="/products" className="navText">
                Products
              </Link>

              <Link href="/about" className="navText">
                About
              </Link>

              <Link href="/contact" className="navText">
                Contact
              </Link>
              <div className="cart-icon">
                <a href="/">
                  <img src="./images/shoppingcart.png" alt="shoppingcart" />
                </a>
              </div>
            </nav>
          </div>
        </header>
        <main>{children}</main>

        <footer>Hello Footer</footer>
      </body>
    </html>
  );
}
