import Image from 'next/image';
import Link from 'next/link';
import { getApples } from '../../database/database';

export const metadata = {
  title: 'Apples page',
  description: 'Generated by create next app',
};

export default async function ApplesPage() {
  const apples = await getApples();

  return (
    <div>
      These are my apples
      {apples.map((apple) => {
        return (
          <div key={`apples-${apple.id}`}>
            <Link href={`/apples/${apple.id}`}>
              <div>{apple.name}</div>
              <Image
                src={`/images/${apple.name.toLowerCase()}.png`}
                width={300}
                height={200}
                alt={apple.name}
              />
            </Link>
          </div>
        );
      })}
    </div>
  );
}
