import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../database/products';

export const metadata = {
  title: 'Apples',
  description: 'Generated by create next app',
};

export default async function ProductsPage() {
  const apples = await getProducts();

  return (
    <div>
      These are my apples
      {apples.map((product) => {
        return (
          <div key={`products-${product.id}`}>
            <Link href={`/apples/${product.id}`}>
              <div>{product.name}</div>
              <Image
                src={`/images/${product.name}.jpeg`}
                width={200}
                height={200}
                alt={product.name}
              />
              <div>
                <h2>{product.name}</h2>
              </div>
              <div>{product.origin}</div>
              <div data-test-id="product-price">{product.price}</div>
            </Link>
          </div>
        );
      })}
    </div>
  );
}
